# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\py\workplace\xm3\pyui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(861, 563)
        TabWidget.setMinimumSize(QtCore.QSize(861, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        TabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(10)
        TabWidget.setFont(font)
        TabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        TabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tab_4.setFont(font)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.getweibo = QtGui.QPushButton(self.tab_4)
        self.getweibo.setGeometry(QtCore.QRect(50, 80, 151, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.getweibo.setFont(font)
        self.getweibo.setObjectName(_fromUtf8("getweibo"))
        self.getzhihu = QtGui.QPushButton(self.tab_4)
        self.getzhihu.setGeometry(QtCore.QRect(50, 330, 151, 101))
        self.getzhihu.setObjectName(_fromUtf8("getzhihu"))
        self.p1 = QtGui.QPushButton(self.tab_4)
        self.p1.setGeometry(QtCore.QRect(340, 210, 111, 51))
        self.p1.setObjectName(_fromUtf8("p1"))
        self.textEdit1 = QtGui.QTextEdit(self.tab_4)
        self.textEdit1.setGeometry(QtCore.QRect(340, 10, 371, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit1.setFont(font)
        self.textEdit1.setObjectName(_fromUtf8("textEdit1"))
        self.textEdit2 = QtGui.QTextEdit(self.tab_4)
        self.textEdit2.setGeometry(QtCore.QRect(340, 280, 371, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(10)
        self.textEdit2.setFont(font)
        self.textEdit2.setObjectName(_fromUtf8("textEdit2"))
        self.p2 = QtGui.QPushButton(self.tab_4)
        self.p2.setGeometry(QtCore.QRect(340, 480, 111, 51))
        self.p2.setObjectName(_fromUtf8("p2"))
        self.n1 = QtGui.QPushButton(self.tab_4)
        self.n1.setGeometry(QtCore.QRect(600, 210, 111, 51))
        self.n1.setObjectName(_fromUtf8("n1"))
        self.n2 = QtGui.QPushButton(self.tab_4)
        self.n2.setGeometry(QtCore.QRect(600, 480, 111, 51))
        self.n2.setObjectName(_fromUtf8("n2"))
        self.zhihu_relogin = QtGui.QPushButton(self.tab_4)
        self.zhihu_relogin.setGeometry(QtCore.QRect(740, 490, 111, 41))
        self.zhihu_relogin.setObjectName(_fromUtf8("zhihu_relogin"))
        self.textEdit_zhihu_user = QtGui.QTextBrowser(self.tab_4)
        self.textEdit_zhihu_user.setGeometry(QtCore.QRect(50, 490, 151, 41))
        self.textEdit_zhihu_user.setObjectName(_fromUtf8("textEdit_zhihu_user"))
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(50, 460, 111, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.zhihu_reply = QtGui.QPushButton(self.tab_4)
        self.zhihu_reply.setGeometry(QtCore.QRect(740, 420, 111, 41))
        self.zhihu_reply.setObjectName(_fromUtf8("zhihu_reply"))
        TabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.dfdf = QtGui.QWidget()
        self.dfdf.setObjectName(_fromUtf8("dfdf"))
        self.sina_textBrowser = QtGui.QTextBrowser(self.dfdf)
        self.sina_textBrowser.setGeometry(QtCore.QRect(350, 20, 441, 401))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.sina_textBrowser.setPalette(palette)
        self.sina_textBrowser.setObjectName(_fromUtf8("sina_textBrowser"))
        self.sina_gn = QtGui.QPushButton(self.dfdf)
        self.sina_gn.setGeometry(QtCore.QRect(120, 120, 141, 61))
        self.sina_gn.setObjectName(_fromUtf8("sina_gn"))
        self.sina_gj = QtGui.QPushButton(self.dfdf)
        self.sina_gj.setGeometry(QtCore.QRect(120, 240, 141, 61))
        self.sina_gj.setObjectName(_fromUtf8("sina_gj"))
        self.sina_sh = QtGui.QPushButton(self.dfdf)
        self.sina_sh.setGeometry(QtCore.QRect(120, 370, 141, 61))
        self.sina_sh.setObjectName(_fromUtf8("sina_sh"))
        self.sina_pre = QtGui.QPushButton(self.dfdf)
        self.sina_pre.setGeometry(QtCore.QRect(350, 450, 141, 51))
        self.sina_pre.setObjectName(_fromUtf8("sina_pre"))
        self.sina_next = QtGui.QPushButton(self.dfdf)
        self.sina_next.setGeometry(QtCore.QRect(640, 450, 151, 51))
        self.sina_next.setObjectName(_fromUtf8("sina_next"))
        self.sina_pic = QtGui.QLabel(self.dfdf)
        self.sina_pic.setGeometry(QtCore.QRect(30, 20, 251, 71))
        self.sina_pic.setText(_fromUtf8(""))
        self.sina_pic.setObjectName(_fromUtf8("sina_pic"))
        TabWidget.addTab(self.dfdf, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.ghtt_textbrowser1 = QtGui.QTextBrowser(self.tab_2)
        self.ghtt_textbrowser1.setGeometry(QtCore.QRect(400, 110, 411, 401))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ghtt_textbrowser1.setPalette(palette)
        self.ghtt_textbrowser1.setObjectName(_fromUtf8("ghtt_textbrowser1"))
        self.ghtt_postedit = QtGui.QTextEdit(self.tab_2)
        self.ghtt_postedit.setGeometry(QtCore.QRect(40, 230, 331, 211))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ghtt_postedit.setPalette(palette)
        self.ghtt_postedit.setObjectName(_fromUtf8("ghtt_postedit"))
        self.ghtt_send = QtGui.QPushButton(self.tab_2)
        self.ghtt_send.setGeometry(QtCore.QRect(252, 460, 111, 41))
        self.ghtt_send.setObjectName(_fromUtf8("ghtt_send"))
        self.ghtt_reset = QtGui.QPushButton(self.tab_2)
        self.ghtt_reset.setGeometry(QtCore.QRect(40, 460, 111, 41))
        self.ghtt_reset.setObjectName(_fromUtf8("ghtt_reset"))
        self.ghtt_combox1 = QtGui.QComboBox(self.tab_2)
        self.ghtt_combox1.setGeometry(QtCore.QRect(400, 30, 411, 41))
        self.ghtt_combox1.setObjectName(_fromUtf8("ghtt_combox1"))
        self.ghtt_crawl_button = QtGui.QPushButton(self.tab_2)
        self.ghtt_crawl_button.setGeometry(QtCore.QRect(120, 140, 171, 71))
        self.ghtt_crawl_button.setAutoRepeatInterval(100)
        self.ghtt_crawl_button.setObjectName(_fromUtf8("ghtt_crawl_button"))
        self.ghtt_pic = QtGui.QLabel(self.tab_2)
        self.ghtt_pic.setGeometry(QtCore.QRect(30, 20, 181, 71))
        self.ghtt_pic.setText(_fromUtf8(""))
        self.ghtt_pic.setObjectName(_fromUtf8("ghtt_pic"))
        TabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.fz_sheng = QtGui.QComboBox(self.tab_3)
        self.fz_sheng.setGeometry(QtCore.QRect(170, 50, 87, 22))
        self.fz_sheng.setObjectName(_fromUtf8("fz_sheng"))
        self.fz_zhong = QtGui.QComboBox(self.tab_3)
        self.fz_zhong.setGeometry(QtCore.QRect(330, 50, 87, 22))
        self.fz_zhong.setObjectName(_fromUtf8("fz_zhong"))
        self.fz_name = QtGui.QComboBox(self.tab_3)
        self.fz_name.setGeometry(QtCore.QRect(490, 50, 341, 22))
        self.fz_name.setObjectName(_fromUtf8("fz_name"))
        self.fz_textEdit1 = QtGui.QTextEdit(self.tab_3)
        self.fz_textEdit1.setGeometry(QtCore.QRect(170, 90, 661, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 189, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 189, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.fz_textEdit1.setPalette(palette)
        self.fz_textEdit1.setObjectName(_fromUtf8("fz_textEdit1"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(30, 50, 111, 71))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName(_fromUtf8("label"))
        self.webView = QtWebKit.QWebView(self.tab_3)
        self.webView.setGeometry(QtCore.QRect(140, 100, 16, 16))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.label_hobby = QtGui.QLabel(self.tab_3)
        self.label_hobby.setGeometry(QtCore.QRect(30, 150, 361, 351))
        self.label_hobby.setText(_fromUtf8(""))
        self.label_hobby.setObjectName(_fromUtf8("label_hobby"))
        self.textEdit = QtGui.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(430, 150, 311, 41))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(760, 150, 71, 61))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 460, 131, 41))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(700, 460, 131, 41))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.textEdit_ha = QtGui.QTextBrowser(self.tab_3)
        self.textEdit_ha.setGeometry(QtCore.QRect(430, 220, 401, 231))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 226, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit_ha.setPalette(palette)
        self.textEdit_ha.setObjectName(_fromUtf8("textEdit_ha"))
        TabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "新闻连连看", None))
        self.getweibo.setText(_translate("TabWidget", "最新热点微博", None))
        self.getzhihu.setText(_translate("TabWidget", "知乎关注内容\n"
"\n"
"(默认账号)", None))
        self.p1.setText(_translate("TabWidget", "上一条", None))
        self.p2.setText(_translate("TabWidget", "上一条", None))
        self.n1.setText(_translate("TabWidget", "下一条", None))
        self.n2.setText(_translate("TabWidget", "下一条", None))
        self.zhihu_relogin.setText(_translate("TabWidget", "切换用户", None))
        self.label_2.setText(_translate("TabWidget", "当前用户", None))
        self.zhihu_reply.setText(_translate("TabWidget", "我要回复", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_4), _translate("TabWidget", "  社交网站  ", None))
        self.sina_gn.setText(_translate("TabWidget", "国内要闻", None))
        self.sina_gj.setText(_translate("TabWidget", "国际热点", None))
        self.sina_sh.setText(_translate("TabWidget", "社会发现", None))
        self.sina_pre.setText(_translate("TabWidget", "保存至桌面", None))
        self.sina_next.setText(_translate("TabWidget", "下一条新闻", None))
        TabWidget.setTabText(TabWidget.indexOf(self.dfdf), _translate("TabWidget", "  新闻速递  ", None))
        self.ghtt_send.setText(_translate("TabWidget", "下条评论", None))
        self.ghtt_reset.setText(_translate("TabWidget", "上条评论", None))
        self.ghtt_crawl_button.setText(_translate("TabWidget", "开始获取", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "  观海听涛  ", None))
        self.label.setText(_translate("TabWidget", "各省新闻网址", None))
        self.pushButton.setText(_translate("TabWidget", "查找", None))
        self.pushButton_2.setText(_translate("TabWidget", "上一条", None))
        self.pushButton_3.setText(_translate("TabWidget", "下一条 ", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "  辅助模块  ", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TabWidget = QtGui.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

