# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\py\workplace\xm3\pyreview.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(691, 630)
        Dialog.setSizeGripEnabled(True)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(170, 20, 481, 561))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.label_weibo = QtGui.QLabel(self.page_5)
        self.label_weibo.setGeometry(QtCore.QRect(50, 30, 370, 350))
        self.label_weibo.setObjectName(_fromUtf8("label_weibo"))
        self.pushButton_weibo_pre = QtGui.QPushButton(self.page_5)
        self.pushButton_weibo_pre.setGeometry(QtCore.QRect(40, 440, 121, 51))
        self.pushButton_weibo_pre.setObjectName(_fromUtf8("pushButton_weibo_pre"))
        self.pushButton_weibo_next = QtGui.QPushButton(self.page_5)
        self.pushButton_weibo_next.setGeometry(QtCore.QRect(300, 440, 121, 51))
        self.pushButton_weibo_next.setObjectName(_fromUtf8("pushButton_weibo_next"))
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.label_zhihu = QtGui.QLabel(self.page_6)
        self.label_zhihu.setGeometry(QtCore.QRect(50, 10, 401, 301))
        self.label_zhihu.setObjectName(_fromUtf8("label_zhihu"))
        self.pushButton_zhihu_pre = QtGui.QPushButton(self.page_6)
        self.pushButton_zhihu_pre.setGeometry(QtCore.QRect(50, 320, 121, 51))
        self.pushButton_zhihu_pre.setObjectName(_fromUtf8("pushButton_zhihu_pre"))
        self.pushButton_zhihu_next = QtGui.QPushButton(self.page_6)
        self.pushButton_zhihu_next.setGeometry(QtCore.QRect(330, 320, 121, 51))
        self.pushButton_zhihu_next.setObjectName(_fromUtf8("pushButton_zhihu_next"))
        self.textEdit = QtGui.QTextEdit(self.page_6)
        self.textEdit.setGeometry(QtCore.QRect(50, 390, 251, 151))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.pushButton_zhihu_reply = QtGui.QPushButton(self.page_6)
        self.pushButton_zhihu_reply.setGeometry(QtCore.QRect(330, 410, 121, 51))
        self.pushButton_zhihu_reply.setObjectName(_fromUtf8("pushButton_zhihu_reply"))
        self.pushButton_zhihu_relogin = QtGui.QPushButton(self.page_6)
        self.pushButton_zhihu_relogin.setGeometry(QtCore.QRect(330, 490, 121, 51))
        self.pushButton_zhihu_relogin.setObjectName(_fromUtf8("pushButton_zhihu_relogin"))
        self.stackedWidget.addWidget(self.page_6)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.label_sina = QtGui.QLabel(self.page)
        self.label_sina.setGeometry(QtCore.QRect(40, 130, 401, 341))
        self.label_sina.setObjectName(_fromUtf8("label_sina"))
        self.pushButton_sina_guonei = QtGui.QPushButton(self.page)
        self.pushButton_sina_guonei.setGeometry(QtCore.QRect(40, 30, 111, 51))
        self.pushButton_sina_guonei.setObjectName(_fromUtf8("pushButton_sina_guonei"))
        self.pushButton_sina_guoji = QtGui.QPushButton(self.page)
        self.pushButton_sina_guoji.setGeometry(QtCore.QRect(180, 30, 111, 51))
        self.pushButton_sina_guoji.setObjectName(_fromUtf8("pushButton_sina_guoji"))
        self.pushButton_sina_shehui = QtGui.QPushButton(self.page)
        self.pushButton_sina_shehui.setGeometry(QtCore.QRect(330, 30, 111, 51))
        self.pushButton_sina_shehui.setObjectName(_fromUtf8("pushButton_sina_shehui"))
        self.pushButton_sina_next = QtGui.QPushButton(self.page)
        self.pushButton_sina_next.setGeometry(QtCore.QRect(30, 500, 111, 51))
        self.pushButton_sina_next.setObjectName(_fromUtf8("pushButton_sina_next"))
        self.pushButton_sina_save = QtGui.QPushButton(self.page)
        self.pushButton_sina_save.setGeometry(QtCore.QRect(330, 500, 111, 51))
        self.pushButton_sina_save.setObjectName(_fromUtf8("pushButton_sina_save"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.comboBox_ghtt = QtGui.QComboBox(self.page_2)
        self.comboBox_ghtt.setGeometry(QtCore.QRect(20, 30, 441, 31))
        self.comboBox_ghtt.setObjectName(_fromUtf8("comboBox_ghtt"))
        self.label_ghtt = QtGui.QLabel(self.page_2)
        self.label_ghtt.setGeometry(QtCore.QRect(30, 80, 431, 261))
        self.label_ghtt.setObjectName(_fromUtf8("label_ghtt"))
        self.label_ghtt_common = QtGui.QLabel(self.page_2)
        self.label_ghtt_common.setGeometry(QtCore.QRect(30, 380, 281, 171))
        self.label_ghtt_common.setObjectName(_fromUtf8("label_ghtt_common"))
        self.pushButton_ghtt_pre = QtGui.QPushButton(self.page_2)
        self.pushButton_ghtt_pre.setGeometry(QtCore.QRect(350, 380, 111, 51))
        self.pushButton_ghtt_pre.setObjectName(_fromUtf8("pushButton_ghtt_pre"))
        self.pushButton_ghtt_next = QtGui.QPushButton(self.page_2)
        self.pushButton_ghtt_next.setGeometry(QtCore.QRect(350, 500, 111, 51))
        self.pushButton_ghtt_next.setObjectName(_fromUtf8("pushButton_ghtt_next"))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.label_hobby = QtGui.QLabel(self.page_3)
        self.label_hobby.setGeometry(QtCore.QRect(40, 20, 421, 421))
        self.label_hobby.setObjectName(_fromUtf8("label_hobby"))
        self.pushButton_hobby_pre = QtGui.QPushButton(self.page_3)
        self.pushButton_hobby_pre.setGeometry(QtCore.QRect(30, 480, 111, 51))
        self.pushButton_hobby_pre.setObjectName(_fromUtf8("pushButton_hobby_pre"))
        self.pushButton_hobby_next = QtGui.QPushButton(self.page_3)
        self.pushButton_hobby_next.setGeometry(QtCore.QRect(350, 480, 111, 51))
        self.pushButton_hobby_next.setObjectName(_fromUtf8("pushButton_hobby_next"))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.comboBox_sheng = QtGui.QComboBox(self.page_4)
        self.comboBox_sheng.setGeometry(QtCore.QRect(30, 20, 91, 31))
        self.comboBox_sheng.setObjectName(_fromUtf8("comboBox_sheng"))
        self.comboBox_shi = QtGui.QComboBox(self.page_4)
        self.comboBox_shi.setGeometry(QtCore.QRect(160, 20, 151, 31))
        self.comboBox_shi.setObjectName(_fromUtf8("comboBox_shi"))
        self.comboBox_zhong = QtGui.QComboBox(self.page_4)
        self.comboBox_zhong.setGeometry(QtCore.QRect(340, 20, 121, 31))
        self.comboBox_zhong.setObjectName(_fromUtf8("comboBox_zhong"))
        self.comboBox_website = QtGui.QComboBox(self.page_4)
        self.comboBox_website.setGeometry(QtCore.QRect(30, 70, 431, 31))
        self.comboBox_website.setObjectName(_fromUtf8("comboBox_website"))
        self.textEdit_fuzhu = QtGui.QTextEdit(self.page_4)
        self.textEdit_fuzhu.setGeometry(QtCore.QRect(30, 140, 271, 41))
        self.textEdit_fuzhu.setObjectName(_fromUtf8("textEdit_fuzhu"))
        self.pushButton_fuzhu_search = QtGui.QPushButton(self.page_4)
        self.pushButton_fuzhu_search.setGeometry(QtCore.QRect(340, 130, 121, 51))
        self.pushButton_fuzhu_search.setObjectName(_fromUtf8("pushButton_fuzhu_search"))
        self.label_fuzhu = QtGui.QLabel(self.page_4)
        self.label_fuzhu.setGeometry(QtCore.QRect(30, 200, 431, 291))
        self.label_fuzhu.setObjectName(_fromUtf8("label_fuzhu"))
        self.pushButton_fuzhu_pre = QtGui.QPushButton(self.page_4)
        self.pushButton_fuzhu_pre.setGeometry(QtCore.QRect(20, 500, 111, 51))
        self.pushButton_fuzhu_pre.setObjectName(_fromUtf8("pushButton_fuzhu_pre"))
        self.pushButton_fuzhu_next = QtGui.QPushButton(self.page_4)
        self.pushButton_fuzhu_next.setGeometry(QtCore.QRect(360, 500, 111, 51))
        self.pushButton_fuzhu_next.setObjectName(_fromUtf8("pushButton_fuzhu_next"))
        self.stackedWidget.addWidget(self.page_4)
        self.pushButton_weibo = QtGui.QPushButton(Dialog)
        self.pushButton_weibo.setGeometry(QtCore.QRect(30, 40, 111, 51))
        self.pushButton_weibo.setObjectName(_fromUtf8("pushButton_weibo"))
        self.pushButton_zhihu = QtGui.QPushButton(Dialog)
        self.pushButton_zhihu.setGeometry(QtCore.QRect(30, 140, 111, 51))
        self.pushButton_zhihu.setObjectName(_fromUtf8("pushButton_zhihu"))
        self.pushButton_sina = QtGui.QPushButton(Dialog)
        self.pushButton_sina.setGeometry(QtCore.QRect(30, 240, 111, 51))
        self.pushButton_sina.setObjectName(_fromUtf8("pushButton_sina"))
        self.pushButton_ghtt = QtGui.QPushButton(Dialog)
        self.pushButton_ghtt.setGeometry(QtCore.QRect(30, 340, 111, 51))
        self.pushButton_ghtt.setObjectName(_fromUtf8("pushButton_ghtt"))
        self.pushButton_hobby = QtGui.QPushButton(Dialog)
        self.pushButton_hobby.setGeometry(QtCore.QRect(30, 440, 111, 51))
        self.pushButton_hobby.setObjectName(_fromUtf8("pushButton_hobby"))
        self.pushButton_fuzhu = QtGui.QPushButton(Dialog)
        self.pushButton_fuzhu.setGeometry(QtCore.QRect(30, 540, 111, 51))
        self.pushButton_fuzhu.setObjectName(_fromUtf8("pushButton_fuzhu"))

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "新闻连连看", None))
        self.label_weibo.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_weibo_pre.setText(_translate("Dialog", "上一条", None))
        self.pushButton_weibo_next.setText(_translate("Dialog", "下一条", None))
        self.label_zhihu.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_zhihu_pre.setText(_translate("Dialog", "上一条", None))
        self.pushButton_zhihu_next.setText(_translate("Dialog", "下一条", None))
        self.pushButton_zhihu_reply.setText(_translate("Dialog", "我要回复", None))
        self.pushButton_zhihu_relogin.setText(_translate("Dialog", "切换账号", None))
        self.label_sina.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_sina_guonei.setText(_translate("Dialog", "国内新闻", None))
        self.pushButton_sina_guoji.setText(_translate("Dialog", "国际新闻", None))
        self.pushButton_sina_shehui.setText(_translate("Dialog", "社会发现", None))
        self.pushButton_sina_next.setText(_translate("Dialog", "下一条新闻", None))
        self.pushButton_sina_save.setText(_translate("Dialog", "保存到桌面", None))
        self.label_ghtt.setText(_translate("Dialog", "TextLabel", None))
        self.label_ghtt_common.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_ghtt_pre.setText(_translate("Dialog", "上一条评论", None))
        self.pushButton_ghtt_next.setText(_translate("Dialog", "下一条评论", None))
        self.label_hobby.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_hobby_pre.setText(_translate("Dialog", "上一条", None))
        self.pushButton_hobby_next.setText(_translate("Dialog", "下一条", None))
        self.pushButton_fuzhu_search.setText(_translate("Dialog", "搜索相关帖子", None))
        self.label_fuzhu.setText(_translate("Dialog", "TextLabel", None))
        self.pushButton_fuzhu_pre.setText(_translate("Dialog", "上一条", None))
        self.pushButton_fuzhu_next.setText(_translate("Dialog", "下一条", None))
        self.pushButton_weibo.setText(_translate("Dialog", "微博热点", None))
        self.pushButton_zhihu.setText(_translate("Dialog", "知乎问答", None))
        self.pushButton_sina.setText(_translate("Dialog", "新闻快递", None))
        self.pushButton_ghtt.setText(_translate("Dialog", "观海听涛", None))
        self.pushButton_hobby.setText(_translate("Dialog", "猜你喜欢", None))
        self.pushButton_fuzhu.setText(_translate("Dialog", "辅助功能", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

